# fly.toml app configuration file generated for sspaback on 2024-01-11T21:32:06-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "intelisepa"
primary_region = "eze"

[build]

[env]

  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
